module.exports = {
    docSidebar: [
        {
            type: 'category',
            label: 'Get Started',
            items: [
                'start',
                'install',
                'faq'
            ],
        },
        {
            type: 'category',
            label: 'General',
            items: [
                'structure',
                'env',
                'command', {
                    Systems: [{
                        type: 'autogenerated',
                        dirName: 'systems',
                    }],
                },
                'xdebug',
            ]
        },
        {
            type: 'category',
            label: 'Advanced',
            items: [
                'makefile',
                'docker-compose',
                'nginx-config',
                'load'
            ],
        },
        {
            type: 'category',
            label: 'About us',
            items: [
                'contributors',
                'community'
            ],
        },
    ],
};
